### ISSUE TITLE
Advanced deploy script for tests

### ISSUE THREAD

**Issue by a-trepalin** [neonlabsorg/neon-evm#520]
We need to add ports inside Dockerfile:

```yaml
services:
  solana:
    container_name: solana
    image: neonlabsorg/solana:${SOLANA_REVISION:-v1.8.12-testnet}
    environment:
      SOLANA_URL: http://solana:8899
      RUST_LOG: solana_runtime::system_instruction_processor=trace,solana_runtime::message_processor=debug,solana_bpf_loader=debug,solana_rbpf=debug
    hostname: solana
    ports:
      - 127.0.0.1:8899:8899
      - 127.0.0.1:8900:8900
      - 127.0.0.1:8001-8009:8001-8009/udp
    expose:
      - "8899"
      - "9900"
      - "8900"
      - "8001"
      - "8001-8009/udp"
```

Furthermore, it would be convenient to make the deploy tests script smarter.

1. Conditional execution — modes — with the creation of keys, with the deployment of EVM, with specific tests.
1. We can also optimize the steps in `deploy-test.sh` so they don't slow things down. Let the script follow them, and not the developer constantly keeps in mind what he needs to do now. As examples:
a. Wait-for-solana will run without delay when the Solana is running.
b. Deploy EVM can be made conditional — only if it differs from the one loaded in the chain.

┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-58) by [Unito](https://www.unito.io)
